apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-products
  template:
    metadata:
      labels:
        app: ms-products
    spec:
      containers:
      - name: ms-products
        image: ms-products:1.0
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: ms-products
spec:
  selector:
    app: ms-products
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
