apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-shopping-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-shopping-cart
  template:
    metadata:
      labels:
        app: ms-shopping-cart
    spec:
      containers:
      - name: ms-shopping-cart
        image: ms-shopping-cart:1.0
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: ms-shopping-cart
spec:
  selector:
    app: ms-shopping-cart
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP
